### ISSUE TITLE
WebAPI Can't read user scope claims

### ISSUE THREAD

**Issue by npnelson** [Azure-Samples/AzureAD-Daemon-DotNet#1]
I got this sample to work, but I'm trying to take it a step further by reading the daemon's permissions so I can decide if it has access to a particular WebAPI call.  For instance, some Daemons might have access to the entire WebAPI- I would give those one Client ID and other Daemon clients might have access to just one or two of the WebAPI methods.  Those would get a separate Client ID which would have a different permission assigned.

In this case, I simply delegated the "Have full access to the To Do List service" to the TodoListDaemon just like this "In the Permissions to Other Applications configuration section, select the TodoListService application, and add the full access delegated permission. Save the configuration."

I set a breakpoint in the TodoListController.Get method to examine the scope claims and they come back null.

```
  public IEnumerable<TodoItem> Get()
        {
            //
            // The Scope claim tells you what permissions the client application has in the service.
            // In this case we look for a scope value of user_impersonation, or full access to the service as the user.
            //
            Claim scopeClaim = ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/scope");

//THIS COMES BACK NULL EVEN THOUGH I ASSIGNED THE Daemon the user_impersonation in Azure portal

            if (scopeClaim != null)
            {
                if (scopeClaim.Value != "user_impersonation")
                {
                    throw new HttpResponseException(new HttpResponseMessage { StatusCode = HttpStatusCode.Unauthorized, ReasonPhrase = "The Scope claim does not contain 'user_impersonation' or scope claim not found" });
                }
            }
```

I would expect to see the user_impersonation claim here, not null.  I've tried different variants, none of which I had any luck with.

What could I be missing?

**Comment by cwe1ss** [comment]
@skwan Has there been any progress on this? Can I get the scope/permissions somehow in a client_credentials call?

**Comment by jmprieur** [comment]
Scopes are about the AAD V2 endpoint (which you get access to using MSAL.Net). this sample is about the AAD V1 endpoint (which you get access token to using ADAL.NET).
