### ISSUE TITLE
Can't get scopeClaim

### ISSUE THREAD

**Issue by xinyi13261611299** [Azure-Samples/AzureAD-Daemon-DotNet#45]
Claim scopeClaim = ClaimsPrincipal.Current.FindFirst("roles");
When I merged the code in the sample into my service, scopeClaim is always null.

I created two applications: QueryProbeClient and QueryProbeService, And configured as instructed.

On the client，I get Access Token through the following code:
`string tenant = "queryprobe.onmicrosoft.com";
            string aadInstance = "https://login.microsoftonline.com/{0}";
            string authority = String.Format(CultureInfo.InvariantCulture, aadInstance, tenant);
            string clientId = "19e4fe1c-d478-4a4b-928d-8122c17b5405";
            string appKey = "****";
            string todoListResourceId = "https://queryprobe.onmicrosoft.com/QueryProbeService";
            AuthenticationContext authContext = new AuthenticationContext(authority);
            ClientCredential clientCredential = new ClientCredential(clientId, appKey);
            AuthenticationResult result = null;
            try
            {
                result = authContext.AcquireToken(todoListResourceId, clientCredential);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return result;`
I got the Access Token and added it to the http header.

On the Service, I added the following code to the startup.cs file:
`public void Configuration(IAppBuilder app)
        {
            try
            {
                app.UseWindowsAzureActiveDirectoryBearerAuthentication(
                    new WindowsAzureActiveDirectoryBearerAuthenticationOptions
                    {
                        Tenant = "queryprobe.onmicrosoft.com",
                        TokenValidationParameters = new TokenValidationParameters
                        {
                            SaveSigninToken = true,
                            ValidAudience = "https://queryprobe.onmicrosoft.com/QueryProbeService"
                        }
                    });
            }
            catch (Exception ex)
            {
                Logger.Info(ex.Message);
                throw ex;
            }
        }`
However, I always get null when I get scopeClaim in the controller file.

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2
